# Generated by Django 5.2 on 2025-04-05 15:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_order_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageTransformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_image', models.ImageField(upload_to='original_images/')),
                ('transformed_image', models.ImageField(upload_to='transformed_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('style', models.CharField(default='ghibli', max_length=100)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
