# Generated by Django 5.1.6 on 2025-04-05 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_imagetransformation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ImageTransformation',
        ),
    ]
